<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJBxu2BN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJBxu2BN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJBxu2BN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJBxu2BN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJBxu2BN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JBxu2BN',
    'container.build_id' => '311f268d',
    'container.build_time' => 1524732230,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJBxu2BN');
