<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.data_persister' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Doctrine/Common/DataPersister.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/DataPersister/ChainDataPersister.php';

return $this->privates['api_platform.data_persister'] = new \ApiPlatform\Core\DataPersister\ChainDataPersister(array(0 => new \ApiPlatform\Core\Bridge\Doctrine\Common\DataPersister(($this->services['doctrine'] ?? $this->getDoctrineService()))));
