<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'api_platform.action.documentation' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Documentation/Action/DocumentationAction.php';

return $this->services['api_platform.action.documentation'] = new \ApiPlatform\Core\Documentation\Action\DocumentationAction(($this->privates['api_platform.metadata.resource.name_collection_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_NameCollectionFactory_CachedService()), 'BetterCallAlphonse API', 'API du site BetterCallAlphonse', '0.0.0', $this->parameters['api_platform.formats']);
